-- MySQL Script generated by MySQL Workbench
-- Fri Apr 16 16:03:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Entiende.me
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Entiende.me
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Entiende.me` DEFAULT CHARACTER SET utf8 ;
USE `Entiende.me` ;

-- -----------------------------------------------------
-- Table `Entiende.me`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`Persona` (
  `idPersona` INT NOT NULL,
  `pnombre` VARCHAR(45) NOT NULL,
  `snombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NOT NULL,
  `sapellido` VARCHAR(45) NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `sexo` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `foto_perfil` LONGBLOB NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`EmpresaDesarrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`EmpresaDesarrollo` (
  `idEmpresaDesarrollo` INT NOT NULL,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `direccion_empresa` VARCHAR(100) NULL,
  `correo_empresa` VARCHAR(50) NOT NULL,
  `fecha_ingreso` DATE NULL,
  PRIMARY KEY (`idEmpresaDesarrollo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`Desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`Desarrollador` (
  `idDesarrollador` INT NOT NULL,
  `d_idPersona` INT NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `mensaje_atributos` VARCHAR(1000) NOT NULL,
  `d_idEmpresaDesarrollo` INT NULL,
  PRIMARY KEY (`idDesarrollador`, `d_idPersona`),
  INDEX `fk_Desarrollador_Persona_idx` (`d_idPersona` ASC),
  INDEX `fk_Desarrollador_EmpresaDesarrollo1_idx` (`d_idEmpresaDesarrollo` ASC),
  CONSTRAINT `fk_Desarrollador_Persona`
    FOREIGN KEY (`d_idPersona`)
    REFERENCES `Entiende.me`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desarrollador_EmpresaDesarrollo1`
    FOREIGN KEY (`d_idEmpresaDesarrollo`)
    REFERENCES `Entiende.me`.`EmpresaDesarrollo` (`idEmpresaDesarrollo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`Cliente` (
  `idCliente` INT NOT NULL,
  `c_idPersona` INT NOT NULL,
  `fecha_registro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`, `c_idPersona`),
  INDEX `fk_Cliente_Persona1_idx` (`c_idPersona` ASC),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`c_idPersona`)
    REFERENCES `Entiende.me`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`PlataformaTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`PlataformaTrabajo` (
  `idPlataformaTrabajo` INT NOT NULL,
  `nombre_plataforma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlataformaTrabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`LenguajeProg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`LenguajeProg` (
  `idLenguajeProg` INT NOT NULL,
  `nombre_lenguaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLenguajeProg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`SolicitudTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`SolicitudTrabajo` (
  `idSolicitudTrabajo` INT NOT NULL,
  `nombre_solicitudtrab` VARCHAR(45) NOT NULL,
  `especificacion_trabajo` VARCHAR(1000) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `tiempo_requerido` VARCHAR(45) NULL,
  `idPlataformaTrabajo` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `c_idPersona` INT NOT NULL,
  `idLenguajeProg` INT NULL,
  PRIMARY KEY (`idSolicitudTrabajo`, `idPlataformaTrabajo`, `idCliente`, `c_idPersona`),
  INDEX `fk_SolicitudTrabajo_PlataformaTrabajo1_idx` (`idPlataformaTrabajo` ASC),
  INDEX `fk_SolicitudTrabajo_Cliente1_idx` (`idCliente` ASC, `c_idPersona` ASC),
  INDEX `fk_SolicitudTrabajo_LenguajeProg1_idx` (`idLenguajeProg` ASC),
  CONSTRAINT `fk_SolicitudTrabajo_PlataformaTrabajo1`
    FOREIGN KEY (`idPlataformaTrabajo`)
    REFERENCES `Entiende.me`.`PlataformaTrabajo` (`idPlataformaTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudTrabajo_Cliente1`
    FOREIGN KEY (`idCliente` , `c_idPersona`)
    REFERENCES `Entiende.me`.`Cliente` (`idCliente` , `c_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudTrabajo_LenguajeProg1`
    FOREIGN KEY (`idLenguajeProg`)
    REFERENCES `Entiende.me`.`LenguajeProg` (`idLenguajeProg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`Trabajo` (
  `idTrabajo` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_entrega` DATE NULL,
  `costo_trabajo` FLOAT NOT NULL,
  `estado_trabajo` VARCHAR(20) NOT NULL,
  `idDesarrollador` INT NOT NULL,
  `d_idPersona` INT NOT NULL,
  `idSolicitudTrabajo` INT NOT NULL,
  `idLenguajeProg` INT NOT NULL,
  PRIMARY KEY (`idTrabajo`, `idDesarrollador`, `d_idPersona`, `idSolicitudTrabajo`, `idLenguajeProg`),
  INDEX `fk_Trabajo_Desarrollador1_idx` (`idDesarrollador` ASC, `d_idPersona` ASC),
  INDEX `fk_Trabajo_SolicitudTrabajo1_idx` (`idSolicitudTrabajo` ASC),
  INDEX `fk_Trabajo_LenguajeProg1_idx` (`idLenguajeProg` ASC),
  CONSTRAINT `fk_Trabajo_Desarrollador1`
    FOREIGN KEY (`idDesarrollador` , `d_idPersona`)
    REFERENCES `Entiende.me`.`Desarrollador` (`idDesarrollador` , `d_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajo_SolicitudTrabajo1`
    FOREIGN KEY (`idSolicitudTrabajo`)
    REFERENCES `Entiende.me`.`SolicitudTrabajo` (`idSolicitudTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajo_LenguajeProg1`
    FOREIGN KEY (`idLenguajeProg`)
    REFERENCES `Entiende.me`.`LenguajeProg` (`idLenguajeProg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`DesarrolladorxPlataformaTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`DesarrolladorxPlataformaTrabajo` (
  `Desarrollador_idDesarrollador` INT NOT NULL,
  `Desarrollador_d_idPersona` INT NOT NULL,
  `PlataformaTrabajo_idPlataformaTrabajo` INT NOT NULL,
  PRIMARY KEY (`Desarrollador_idDesarrollador`, `Desarrollador_d_idPersona`, `PlataformaTrabajo_idPlataformaTrabajo`),
  INDEX `fk_Desarrollador_has_PlataformaTrabajo_PlataformaTrabajo1_idx` (`PlataformaTrabajo_idPlataformaTrabajo` ASC),
  INDEX `fk_Desarrollador_has_PlataformaTrabajo_Desarrollador1_idx` (`Desarrollador_idDesarrollador` ASC, `Desarrollador_d_idPersona` ASC),
  CONSTRAINT `fk_Desarrollador_has_PlataformaTrabajo_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador` , `Desarrollador_d_idPersona`)
    REFERENCES `Entiende.me`.`Desarrollador` (`idDesarrollador` , `d_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desarrollador_has_PlataformaTrabajo_PlataformaTrabajo1`
    FOREIGN KEY (`PlataformaTrabajo_idPlataformaTrabajo`)
    REFERENCES `Entiende.me`.`PlataformaTrabajo` (`idPlataformaTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entiende.me`.`DesarrolladorxLenguajeProg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entiende.me`.`DesarrolladorxLenguajeProg` (
  `Desarrollador_idDesarrollador` INT NOT NULL,
  `Desarrollador_d_idPersona` INT NOT NULL,
  `LenguajeProg_idLenguajeProg` INT NOT NULL,
  PRIMARY KEY (`Desarrollador_idDesarrollador`, `Desarrollador_d_idPersona`, `LenguajeProg_idLenguajeProg`),
  INDEX `fk_Desarrollador_has_LenguajeProg_LenguajeProg1_idx` (`LenguajeProg_idLenguajeProg` ASC),
  INDEX `fk_Desarrollador_has_LenguajeProg_Desarrollador1_idx` (`Desarrollador_idDesarrollador` ASC, `Desarrollador_d_idPersona` ASC),
  CONSTRAINT `fk_Desarrollador_has_LenguajeProg_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador` , `Desarrollador_d_idPersona`)
    REFERENCES `Entiende.me`.`Desarrollador` (`idDesarrollador` , `d_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desarrollador_has_LenguajeProg_LenguajeProg1`
    FOREIGN KEY (`LenguajeProg_idLenguajeProg`)
    REFERENCES `Entiende.me`.`LenguajeProg` (`idLenguajeProg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
